# Generated by Django 2.0.4 on 2018-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
